version: "3"

services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  web:
    build: ./app
    container_name: back
    command: uvicorn handlers.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  front:
    build: ./front
    container_name: front
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
